centerpose_track:
  method: centerpose_track
  # Add any method-specific parameters here
  # 3D Bounding Box keypoint horizontally flip
  flip_idx: [[1, 5], [3, 7], [2, 6], [4, 8]]
  input_res: 512
  output_res: 512

# {0, 1} = {False, True}
augmentation:
  color_aug: 1
  crop_aug: 1
  flip_aug: 1
  rot_aug: 1